fix(ci): update rust toolchain to fix dependency issue
Fixes the following error:

error: failed to compile `bpf-linker v0.9.14`, intermediate artifacts can be found at `/tmp/cargo-installZfKBMc`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Caused by:
  rustc 1.86.0 is not supported by the following packages:
    time@0.3.46 requires rustc 1.88.0
    time-core@0.1.8 requires rustc 1.88.0
  Try re-running `cargo install` with `--locked`
Error: Process completed with exit code 101.

Signed-off-by: irozzo-1A <iacopo@sysdig.com>