fix(ci): Bump the rust toolchain to 1.91.1
Bump the rust toolchain to 1.91.1. Fixes the following:

    error: rustc 1.88.0 is not supported by the following packages:
      aws-config@1.8.15 requires rustc 1.91.1
      aws-credential-types@1.2.14 requires rustc 1.91.1
      aws-runtime@1.7.2 requires rustc 1.91.1
      [ and many more ]

Signed-off-by: Gerald Combs <gerald@wireshark.org>